# This file has been autogenerated in 'extras/ModuleMaintenance.R'. Do not change by hand. 
library(SelfControlledCaseSeries)

createCohortMethodModuleSpecifications <- function(nestingCohortDatabaseSchema = cdmDatabaseSchema,
                                                   sccsAnalysisList,
                                                   exposuresOutcomeList,
                                                   analysesToExclude = NULL,
                                                   combineDataFetchAcrossOutcomes = FALSE) {
  analysis <- list()
  for (name in names(formals(createCohortMethodModuleSpecifications))) {
    analysis[[name]] <- get(name)
  }

  specifications <- list(module = "SelfControlledCaseSeriesModule",
                         version = "0.0.1",
                         remoteRepo = "github.com",
                         remoteUsername = "ohdsi",
                         settings = analysis)
  class(specifications) <- c("SelfControlledCaseSeriesModuleSpecifications", "ModuleSpecifications")
  return(specifications)
}
