# This file has been autogenerated in 'extras/ModuleMaintenance.R'. Do not change by hand. 
library(SelfControlledCaseSeries)

creatSelfControlledCaseSeriesModuleSpecifications <- function(sccsAnalysisList,
                                                              exposuresOutcomeList,
                                                              analysesToExclude = NULL,
                                                              combineDataFetchAcrossOutcomes = FALSE,
                                                              sccsDiagnosticThresholds = createSccsDiagnosticThresholds()) {
  analysis <- list()
  for (name in names(formals(creatSelfControlledCaseSeriesModuleSpecifications))) {
    analysis[[name]] <- get(name)
  }

  specifications <- list(module = "SelfControlledCaseSeriesModule",
                         version = "0.1.3",
                         remoteRepo = "github.com",
                         remoteUsername = "ohdsi",
                         settings = analysis)
  class(specifications) <- c("SelfControlledCaseSeriesModuleSpecifications", "ModuleSpecifications")
  return(specifications)
}
