# Copyright 2022 Observational Health Data Sciences and Informatics
#
# This file is part of SelfControlledCaseSeriesModule
# 
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
# 
#     http://www.apache.org/licenses/LICENSE-2.0
# 
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# Format and check code:
OhdsiRTools::updateCopyrightYearFolder()
OhdsiRTools::findNonAsciiStringsInFolder()

# Generate settings function
moduleInfo <- ParallelLogger::loadSettingsFromJson("MetaData.json")
message(sprintf("Using module version '%s' in settings function.", moduleInfo$Version))
library(SelfControlledCaseSeries)
rCode <- c("# This file has been autogenerated in 'extras/ModuleMaintenance.R'. Do not change by hand. ")
rCode <- c(rCode, "library(SelfControlledCaseSeries)")
rCode <- ParallelLogger::createArgFunction(functionName = 'runSccsAnalyses',
                                           excludeArgs = c("connectionDetails",
                                                           "cdmDatabaseSchema",
                                                           "tempEmulationSchema",
                                                           "exposureDatabaseSchema",
                                                           "exposureTable",
                                                           "outcomeDatabaseSchema",
                                                           "outcomeTable",
                                                           "customCovariateDatabaseSchema",
                                                           "customCovariateTable",
                                                           "NestingCohortDatabaseSchema",
                                                           "nestingCohortTable",
                                                           "cdmVersion",
                                                           "outputFolder",
                                                           "sccsMultiThreadingSettings"),
                                           newName = "createCohortMethodModuleSpecifications",
                                           rCode = rCode)
rCode <- rCode[-grep("^#'", rCode)]
rCode <- rCode[-grep("class\\(analysis\\)", rCode)]
rCode[grep("return\\(analysis\\)", rCode)]  <- sprintf("
  specifications <- list(module = \"%s\",
                         version = \"%s\",
                         remoteRepo = \"github.com\",
                         remoteUsername = \"ohdsi\",
                         settings = analysis)
  class(specifications) <- c(\"SelfControlledCaseSeriesModuleSpecifications\", \"ModuleSpecifications\")
  return(specifications)", moduleInfo$Name, moduleInfo$Version)
writeLines(rCode, "SettingsFunctions.R")


# Generate renv lock file and activate renv:
OhdsiRTools::createRenvLockFile(rootPackage = "SelfControlledCaseSeries",
                                includeRootPackage = TRUE,
                                mode = "description",
                                additionalRequiredPackages = c("checkmate", 
                                                               "testthat",
                                                               "Eunomia",
                                                               "CohortGenerator"))
renv::init()
